/**
 * Development driver: photos on the local filesystem.
 *
 * Deliberately not for production — a serverless filesystem is ephemeral and
 * not shared between instances, so anything written here would vanish. It
 * exists so the photo feature can be built and used locally without a Vercel
 * Blob account or token.
 */

// Importing this from a client component is a build error, not a runtime
// one — which is the point. Three separate bugs in this project were a
// client component pulling a server module in through a shared constant.
import "server-only";

import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join, normalize, resolve, sep } from "node:path";
import type { PhotoStorage, StoredPhoto } from "./storage";

/** Kept out of git; see .gitignore. */
const ROOT = resolve(process.cwd(), ".photos");

/**
 * Refuses any path that would escape the storage directory. Paths are
 * generated by `photoPath` rather than supplied by users, but a traversal bug
 * here would expose the whole filesystem, so it is checked anyway.
 */
function resolveWithin(path: string): string {
  const full = resolve(ROOT, normalize(path));
  if (full !== ROOT && !full.startsWith(ROOT + sep)) {
    throw new Error("Refusing to read or write outside the photo directory.");
  }
  return full;
}

const CONTENT_TYPES: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
};

function contentTypeFor(path: string): string {
  const extension = path.split(".").pop()?.toLowerCase() ?? "";
  return CONTENT_TYPES[extension] ?? "application/octet-stream";
}

export function createLocalStorage(): PhotoStorage {
  return {
    async put(path: string, data: Buffer): Promise<StoredPhoto> {
      const full = resolveWithin(path);
      await mkdir(dirname(full), { recursive: true });
      await writeFile(full, data);
      return { path, bytes: data.byteLength };
    },

    async get(path: string) {
      try {
        const data = await readFile(resolveWithin(path));
        return { data, contentType: contentTypeFor(path) };
      } catch {
        // A missing file is a missing photo, not a crash — the database row
        // can outlive the file if the directory was cleared.
        return null;
      }
    },

    async delete(path: string) {
      try {
        await unlink(resolveWithin(path));
      } catch {
        // Already gone is the desired end state.
      }
    },
  };
}

export const LOCAL_PHOTO_ROOT = join(ROOT);
